services:
  mysql-server:
    image: mysql:8.0-oracle
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
      - --log-bin=mysql-bin
      - --log_bin_trust_function_creators=1
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data:
